Repository SSAFY-byuri/Unbreakable_Mind_Algorithm, pull requests merged in 2023-02, with the labels that each got.

#28 고우민 : BOJ_15683_G4_감시_Add
  고우민/week2/BOJ_15683_G4_감시.java
Labels: DFS, Simulation

#29 유승민 : BOJ_3954_G1_Brainfk 인터프리터_Add
  유승민/Pull_Request_Template.md
  유승민/week2/BOJ_3954_G1_Brainfk 인터프리터.cpp
Labels: Simulation, Stack

#30 고우민 : PG_L3_합승택시요금_Add
  고우민/week2/PG_L3_합승택시요금.java
Labels: Graph

#34 고우민 : BOJ_17142_G3_연구소3_Add
  고우민/week1/BOJ_14502_G4_연구소.java
  고우민/week2/BOJ_17142_G3_연구소3.java
Labels: BFS, Combination

#37 고우민 : BOJ_3190_G4_뱀.Add
  고우민/week2/BOJ_3190_G4_뱀.java
Labels: Queue, Simulation

#38 고우민 : BOJ_1759_G5_암호만들기_Fix
  고우민/week3/BOJ_1759_G5_암호만들기.java
Labels: Combination

#39 유승민 : BOJ_27313_G3_효율적인 애니메이션 감상_Add
  유승민/Pull_Request_Template.md
  유승민/week3/BOJ_27313_G3_효율적인 애니메이션 감상.cpp
Labels: Greedy

#40 유승민 : BOJ_1759_G5_암호 만들기_Add
  유승민/Pull_Request_Template.md
  유승민/week3/BOJ_1759_G5_암호 만들기.cpp
Labels: Combination, Brute Force

#41 유승민 : BOJ_5719_P5_거의 최단 경로_Add
  유승민/Pull_Request_Template.md
  유승민/week3/BOJ_5719_P5_거의 최단 경로.cpp
Labels: Dijkstra, Graph

#43 유연석 : BOJ_1759_G5_암호만들기_Add
  유연석/Pull_Request_Template.md
  유연석/week1/BOJ_1012_S2_유기농배추.java
  유연석/week2/BOJ_15683_G4_감시.java
  유연석/week3/BOJ_1759_G5_암호만들기.java
Labels: Combination

#52 유승민 : BOJ_3015_P5_오아시스 재결합_Add
  유승민/Pull_Request_Template.md
  유승민/week3/BOJ_3015_P5_오아시스 재결합.cpp
Labels: Stack

#53 고우민 : BOJ_5719_P5_거의최단경로_Add
  고우민/week3/BOJ_2447_G5_별찍기.java
  고우민/week3/BOJ_5719_P5_거의최단경로.java
Labels: Dijkstra

#54 유승민 : BOJ_14942_P5_개미_Add
  유승민/Pull_Request_Template.md
  유승민/week3/BOJ_14942_P5_개미.cpp
Labels: Tree

#62 고우민 : PG_L2_양궁대회_Add
  고우민/week4/BOJ_1655_G2_가운데를말해요.java
  고우민/week4/BOJ_3190_G4_뱀.java
  고우민/week4/PG_L2_양궁대회.java
  고우민/week4/PG_L2_택배상자.java
Labels: DFS

#65 유승민 : BOJ_5670_P4_휴대폰 자판_Add
  유승민/Pull_Request_Template.md
  유승민/week4/BOJ_5670_P4_휴대폰 자판.cpp
Labels: Tree

#68 유연석: PG_L3_네트워크_add
  유연석/Pull_Request_Template.md
  유연석/week4/PG_L2_택배상자.java
  유연석/week5/PG_L2_게임맵최단거리.java
  유연석/week5/PG_L2_타겟넘버.java
  유연석/week5/PG_L3_네트워크.java
  유연석/week5/PG_L3_단어변환.java
Labels: BFS, DFS
